language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    branch: master

branches:
  only: master

install:
  - npm i
  - npm i -g codecov

script:
  - npm test
  - codecov